language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ssabin/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true ssabin/docker-react npm run test

